### ISSUE TITLE
Does not compile against latest Adafruit_GFX

### ISSUE THREAD

**Issue by braitsch** [markruys/arduino-Max72xxPanel#1]
Works with Adafruit_GFX June 11.2013 and earlier. Below are the errors I receive when attempting to compile against the lastest Adafruit_GFX (July 05.2013)

```
Max72xxPanel.cpp: In constructor 'Max72xxPanel::Max72xxPanel(byte, byte, byte)':
Max72xxPanel.cpp:37: error: no matching function for call to 'Adafruit_GFX::Adafruit_GFX()'
Adafruit_GFX.h:17: note: candidates are: Adafruit_GFX::Adafruit_GFX(int16_t, int16_t)
Adafruit_GFX.h:13: note: Adafruit_GFX::Adafruit_GFX(const Adafruit_GFX&)
```

**Comment by markruys** [comment]
Thanks for the report. I just commited an update to support the Adafruit-GFX-library dated July 5th. Unfortunately not backwards compatible.
